# This is a basic workflow to help you get started with Actions

name: Publish

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
 publish:
     # needs: [build]
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
      steps:
          - uses: actions/checkout@v4.1.1
          - uses: actions/setup-java@v3
            with:
              java-version: '11'
              distribution: 'temurin'
          - name: Publish package
            run: mvn --batch-mode deploy
            env:
              PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
